import { ReleaseItem } from "./store/interface";

export const goods = [
    {
      name: 'Z NJZ702MLFS-AR',
      company: 'Daiwa',
      collection: 'Ninja',
      group: 'Удилища',
      subgroup:'Спиннинг',
      description: 'Описание',
      img: '',
    },
    {
      name: 'Z NJZ802MFS-AR',
      company: 'Daiwa',
      collection: 'Ninja',
      group: 'Удилища',
      subgroup:'Спиннинг',
      description: 'Описание',
      img: '',
    },
    {
      name: 'Z NJZ802MHFS-AR',
      company: 'Daiwa',
      collection: 'Ninja',
      group: 'Удилища',
      subgroup:'Спиннинг',
      description: 'Описание',
      img: '',
    },
  
    {
      name: 'Branzino EX AGS 94MMH',
      company: 'Daiwa',
      collection: 'Morethan',
      group: 'Удилища',
      subgroup:'Спиннинг',
      description: 'Описание',
      img: '',
    },
    {
      name: 'Branzino EX AGS 98M/MH',
      company: 'Daiwa',
      collection: 'Morethan',
      group: 'Удилища',
      subgroup:'Фидер',
      description: 'Описание',
      img: '',
    },
    {
      name: 'Branzino EX AGS 99I/LH',
      company: 'Daiwa',
      collection: 'Morethan',
      group: 'Удилища',
      subgroup:'Кастинг',
      description: 'Описание',
      img: '',
    },
    {
      name: 'FC LT 1000S',
      company: 'Daiwa',
      collection: 'Freams',
      group: 'Катушки',
      subgroup:'Безинерционные',
      description: 'Описание',
      img: '',
    },
    {
      name: 'LT 2500',
      company: 'Daiwa',
      collection: 'Freams',
      group: 'Катушки',
      subgroup:'Мультипликатор',
      description: 'Описание',
      img: '',
    },
    {
      name: 'LT 3000',
      company: 'Daiwa',
      collection: 'Freams',
      group: 'Катушки',
      subgroup:'Безинерционные',
      description: 'Описание',
      img: '',
    },
    {
      name: 'E LT 2000S',
      company: 'Daiwa',
      collection: 'Lexa',
      group: 'Катушки',
      subgroup:'Безинерционные',
      description: 'Описание',
      img: '',
    },
    {
      name: 'E LT 2500',
      company: 'Daiwa',
      collection: 'Lexa',
      group: 'Катушки',
      subgroup:'Безинерционные',
      description: 'Описание',
      img: '',
    },
    {
      name: 'E LT 3000',
      company: 'Daiwa',
      collection: 'Lexa',
      group: 'Катушки',
      subgroup:'Безинерционные',
      description: 'Описание',
      img: '',
    },
  ]
  
    export const NewRealisesItem: ReleaseItem[] = [
      {
        picture: "/images/newReliases/блесна зеленая.jpg",
        text: "Вращающаяся блесна Yarie №672 Blender, 4.2 гр, SP6",
        price: 630,
      },
      {
        picture: "/images/newReliases/Кейс-чехол.jpg",
        text: "Кейс-чехол Garry Zonter, S, серый",
        price: 2399,
      },
      {
        picture: "/images/newReliases/колебалка голубая.jpg",
        text: "Колеблющаяся блесна Yarie №706 T-Spoon, 1.4 гр, BS-10",
        price: 495,
      },
      {
        picture: "/images/newReliases/колебалка розовая.jpg",
        text: "Колеблющаяся блесна Yarie №713 First Star, 10 г, A6",
        price: 530,
      },
      {
        picture: "/images/newReliases/спиннинг.jpg",
        text: "Спиннинг Zetrix Tezza TZS-732ML, 223 см, 2-12 г",
        price: 6480,
      },
      {
        picture: "/images/newReliases/цикада.jpg",
        text: "Раттлин Lucky Craft Air Claw S, 2.8 г, #Blow Brown Glow",
        price: 1095,
      },
    ];
    